if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="main-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import graph;
unitsize(2cm);
pair A=(0,0),B=(4,0),C=(0,2),D=(0.5,0),E=(1.5,0),F=(1.8,0);
pair G=(3,2),I=(0,0.8),J=(4,0.8),H=(2.7,0.8),K=(2.2,0);
draw(A--B,Arrow());
draw(A--C,Arrow());
draw(F--G,black+2bp);
path ligne=F{dir(45)}..(3,1)..{dir(45)}(3.8,1.5);
draw(ligne);
draw(K--H,dashed);
dot("$b(t)$",H);
draw(I--J,dashed);
label("$x=\frac{s}{2}t+b(0)$",(2.3,1));
label("$x=\frac{s}{2}t+c$",(3,0.5));
dot("$x_1(0)$",D,S);
dot("$x_2(0)$",E,N);
dot("$b(0)$",F,S);
label("$x$",B,S);
label("$t$",C,E);
dot("$x-\frac{s}{2}t$",K,SE);
