
%matriz laplaciana
Ap = sparse( [II; II; II; II; II;...              % interior
              ...
              IN; IN; IN; IN; ...
              IS; IS; IS; IS;... % norte, sur
              ...
              IW; IW; IW; IW; IW; ... % oeste, este
              IE; IE; IE; IE; IE;... 
              ... 
              INW; INW; INW; INW; ... % P(INW)=0
              INE; INE; INE; INE; ...  
              ISW; ISW; ISW; ISW; ... % esquinas inferiores
              ISE; ISE; ISE; ISE],...  
        [II; II+NX; II-NX; II+1; II-1;...
             ...
              IN; IN-NX; IN+1; IN-1; ...
              IS; IS+NX; IS+1; IS-1;...
              ...
              IW; IW+NX; IW-NX; IW+1; IE;  ...
              IE; IE+NX; IE-NX; IW; IE-1;...
              ... 
              INW; INW-NX; INW+1; INE;... 
              INE; INE-NX; INW; INE-1; ...
              ISW; ISW+NX; ISE; ISW+1; ...
              ISE; ISE+NX; ISE-1; ISW], ...
        [-4+0*II; 1+0*II; 1+0*II; 1+0*II; 1+0*II;...
             ...
              -3+0*IN; 1+0*IN; 1+0*IN; 1+0*IN;...
              -3+0*IS; 1+0*IS; 1+0*IS; 1+0*IS;...
              ...
              -4+0*IW; 1+0*IW; 1+0*IW; 1+0*IW; 1+0*IW; ...
              -4+0*IE; 1+0*IE; 1+0*IE; 1+0*IE; 1+0*IE;... 
               1; 0; 0; 0;... %P(INW)=0
              -3; 1; 1; 1;...
              -3; 1; 1; 1;...
              -3; 1; 1; 1]);
